edition = "2023";

package example.editions2023;

import "tagger/tagger.proto";

option go_package = "github.com/srikrsna/protoc-gen-gotag/example/editions2023";

message Example {
    string with_new_tags = 1 [(tagger.tags) = "graphql:\"withNewTags,optional\"" ];
    string with_new_multiple = 2 [(tagger.tags) = "graphql:\"withNewTags,optional\" xml:\"multi,omitempty\"" ];

    string replace_default = 3 [(tagger.tags) = "json:\"replacePrevious\""] ;
    string implicit_presence = 4 [features.field_presence = IMPLICIT, (tagger.tags) = "json:\"implicit\""];

    oneof one_of {
        option (tagger.oneof_tags) = "graphql:\"withNewTags,optional\"";
        string a = 5 [(tagger.tags) = "json:\"A\""];
        int32 b_jk = 6 [(tagger.tags) = "json:\"b_Jk\""];
    }
}

message ThirdExample {
    message InnerExample {
        string id = 1 [(tagger.tags) = "json:\"yes\""];
        int32 yes = 2 [(tagger.tags) = "json:\"id\""];
    }

    InnerExample inner_example = 1 [(tagger.tags) = "json:\"inner\""];
}
