edition = "2024";

package example.editions2024;

import "tagger/tagger.proto";
import option "google/protobuf/go_features.proto";

option go_package = "github.com/bosonicalcom/protoc-gen-gotag/example/editions2024";

// gotag can only tag exported struct fields, so the Open (or Hybrid) Go API is required.
option features.(pb.go).api_level = API_OPEN;

message Example {
    string with_new_tags = 1 [(tagger.tags) = "graphql:\"withNewTags,optional\"" ];
    string with_new_multiple = 2 [(tagger.tags) = "graphql:\"withNewTags,optional\" xml:\"multi,omitempty\"" ];

    string replace_default = 3 [(tagger.tags) = "json:\"replacePrevious\""] ;
    string implicit_presence = 4 [features.field_presence = IMPLICIT, (tagger.tags) = "json:\"implicit\""];

    oneof one_of {
        option (tagger.oneof_tags) = "graphql:\"withNewTags,optional\"";
        string a = 5 [(tagger.tags) = "json:\"A\""];
        int32 b_jk = 6 [(tagger.tags) = "json:\"b_Jk\""];
    }
}

message ThirdExample {
    message InnerExample {
        string id = 1 [(tagger.tags) = "json:\"yes\""];
        int32 yes = 2 [(tagger.tags) = "json:\"id\""];
    }

    InnerExample inner_example = 1 [(tagger.tags) = "json:\"inner\""];
}
