// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.2
// source: example/editions2024/editions2024.proto

package editions2024

import (
	_ "github.com/bosonicalcom/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Example struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags      *string                `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple  *string                `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault   *string                `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault" json:"replacePrevious"`
	ImplicitPresence string                 `protobuf:"bytes,4,opt,name=implicit_presence,json=implicitPresence" json:"implicit"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*Example_A
	//	*Example_BJk
	OneOf         isExample_OneOf `protobuf_oneof:"one_of" graphql:"withNewTags,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_example_editions2024_editions2024_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_example_editions2024_editions2024_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_example_editions2024_editions2024_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetWithNewTags() string {
	if x != nil && x.WithNewTags != nil {
		return *x.WithNewTags
	}
	return ""
}

func (x *Example) GetWithNewMultiple() string {
	if x != nil && x.WithNewMultiple != nil {
		return *x.WithNewMultiple
	}
	return ""
}

func (x *Example) GetReplaceDefault() string {
	if x != nil && x.ReplaceDefault != nil {
		return *x.ReplaceDefault
	}
	return ""
}

func (x *Example) GetImplicitPresence() string {
	if x != nil {
		return x.ImplicitPresence
	}
	return ""
}

func (x *Example) GetOneOf() isExample_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *Example) GetA() string {
	if x != nil {
		if x, ok := x.OneOf.(*Example_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *Example) GetBJk() int32 {
	if x != nil {
		if x, ok := x.OneOf.(*Example_BJk); ok {
			return x.BJk
		}
	}
	return 0
}

type isExample_OneOf interface {
	isExample_OneOf()
}

type Example_A struct {
	A string `protobuf:"bytes,5,opt,name=a,oneof" json:"A"`
}

type Example_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,oneof" json:"b_Jk"`
}

func (*Example_A) isExample_OneOf() {}

func (*Example_BJk) isExample_OneOf() {}

type ThirdExample struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	InnerExample  *ThirdExample_InnerExample `protobuf:"bytes,1,opt,name=inner_example,json=innerExample" json:"inner"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample) Reset() {
	*x = ThirdExample{}
	mi := &file_example_editions2024_editions2024_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample) ProtoMessage() {}

func (x *ThirdExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_editions2024_editions2024_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample.ProtoReflect.Descriptor instead.
func (*ThirdExample) Descriptor() ([]byte, []int) {
	return file_example_editions2024_editions2024_proto_rawDescGZIP(), []int{1}
}

func (x *ThirdExample) GetInnerExample() *ThirdExample_InnerExample {
	if x != nil {
		return x.InnerExample
	}
	return nil
}

type ThirdExample_InnerExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"yes"`
	Yes           *int32                 `protobuf:"varint,2,opt,name=yes" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample_InnerExample) Reset() {
	*x = ThirdExample_InnerExample{}
	mi := &file_example_editions2024_editions2024_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample_InnerExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample_InnerExample) ProtoMessage() {}

func (x *ThirdExample_InnerExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_editions2024_editions2024_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample_InnerExample.ProtoReflect.Descriptor instead.
func (*ThirdExample_InnerExample) Descriptor() ([]byte, []int) {
	return file_example_editions2024_editions2024_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ThirdExample_InnerExample) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ThirdExample_InnerExample) GetYes() int32 {
	if x != nil && x.Yes != nil {
		return *x.Yes
	}
	return 0
}

var File_example_editions2024_editions2024_proto protoreflect.FileDescriptor

const file_example_editions2024_editions2024_proto_rawDesc = "" +
	"\n" +
	"'example/editions2024/editions2024.proto\x12\x14example.editions2024\x1a\x13tagger/tagger.proto\"\xbc\x03\n" +
	"\aExample\x12G\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB#\x9a\x84\x9e\x03\x1egraphql:\"withNewTags,optional\"R\vwithNewTags\x12e\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB9\x9a\x84\x9e\x034graphql:\"withNewTags,optional\" xml:\"multi,omitempty\"R\x0fwithNewMultiple\x12D\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x1b\x9a\x84\x9e\x03\x16json:\"replacePrevious\"R\x0ereplaceDefault\x12F\n" +
	"\x11implicit_presence\x18\x04 \x01(\tB\x19\x9a\x84\x9e\x03\x0fjson:\"implicit\"\xaa\x01\x02\b\x02R\x10implicitPresence\x12\x1d\n" +
	"\x01a\x18\x05 \x01(\tB\r\x9a\x84\x9e\x03\bjson:\"A\"H\x00R\x01a\x12%\n" +
	"\x04b_jk\x18\x06 \x01(\x05B\x10\x9a\x84\x9e\x03\vjson:\"b_Jk\"H\x00R\x03bJkB-\n" +
	"\x06one_of\x12#\x9a\x84\x9e\x03\x1egraphql:\"withNewTags,optional\"\"\xca\x01\n" +
	"\fThirdExample\x12g\n" +
	"\rinner_example\x18\x01 \x01(\v2/.example.editions2024.ThirdExample.InnerExampleB\x11\x9a\x84\x9e\x03\fjson:\"inner\"R\finnerExample\x1aQ\n" +
	"\fInnerExample\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\tB\x0f\x9a\x84\x9e\x03\n" +
	"json:\"yes\"R\x02id\x12 \n" +
	"\x03yes\x18\x02 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x03yesBGZ=github.com/bosonicalcom/protoc-gen-gotag/example/editions2024\x92\x03\x05\xd2>\x02\x10\x01b\beditionsp\xe9\az!google/protobuf/go_features.proto"

var (
	file_example_editions2024_editions2024_proto_rawDescOnce sync.Once
	file_example_editions2024_editions2024_proto_rawDescData []byte
)

func file_example_editions2024_editions2024_proto_rawDescGZIP() []byte {
	file_example_editions2024_editions2024_proto_rawDescOnce.Do(func() {
		file_example_editions2024_editions2024_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_editions2024_editions2024_proto_rawDesc), len(file_example_editions2024_editions2024_proto_rawDesc)))
	})
	return file_example_editions2024_editions2024_proto_rawDescData
}

var file_example_editions2024_editions2024_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_editions2024_editions2024_proto_goTypes = []any{
	(*Example)(nil),                   // 0: example.editions2024.Example
	(*ThirdExample)(nil),              // 1: example.editions2024.ThirdExample
	(*ThirdExample_InnerExample)(nil), // 2: example.editions2024.ThirdExample.InnerExample
}
var file_example_editions2024_editions2024_proto_depIdxs = []int32{
	2, // 0: example.editions2024.ThirdExample.inner_example:type_name -> example.editions2024.ThirdExample.InnerExample
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_editions2024_editions2024_proto_init() }
func file_example_editions2024_editions2024_proto_init() {
	if File_example_editions2024_editions2024_proto != nil {
		return
	}
	file_example_editions2024_editions2024_proto_msgTypes[0].OneofWrappers = []any{
		(*Example_A)(nil),
		(*Example_BJk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_editions2024_editions2024_proto_rawDesc), len(file_example_editions2024_editions2024_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_editions2024_editions2024_proto_goTypes,
		DependencyIndexes: file_example_editions2024_editions2024_proto_depIdxs,
		MessageInfos:      file_example_editions2024_editions2024_proto_msgTypes,
	}.Build()
	File_example_editions2024_editions2024_proto = out.File
	file_example_editions2024_editions2024_proto_goTypes = nil
	file_example_editions2024_editions2024_proto_depIdxs = nil
}
